### ISSUE TITLE
Add Certificate/Rating tracking

### ISSUE THREAD

**Issue by amschmitt** [amschmitt/EFLProject#1]
**Add the ability to choose a certificate to work on**
A pilot's total time in each different category would apply to the time requirements of the different certificates/ratings. This would be displayed on a dashboard on the home page, as well as on its own dedicated page for managing certificates.

Tasks:
- [ ] Design/create table(s) that will store certificate info by user
- [ ] Design/create table to store available certificates and requirements
- [ ] Design/create table(s) that will store aggregate time info (for example, total instrument time)
- [ ] Write Postgres functions that will aggregate certificate type and time required/logged
- [ ] Manage Record page in html
    - [ ] Certificate view, displays each current (former?) certificate and detailed progress
    - [ ] On create certificate, ask pilot for each category of time, apply to certificate?
    - [ ] Begin new certificate button, choose from dropdown/modal
    - [ ] Complete certificate button, on certificate view
- [ ] Add method of choosing whether to apply time to active certificate on Add Log Entry html page
- [ ] WebAPI
    - [ ] HTTP GET user certificates and total time info
    - [ ] HTTP POST new user certificate
    - [ ] Java database hits to provide HTTP response data and POST INSERTs
- [ ] Dashboard on home screen
    - [ ] Abridged view of active certificates
    - [ ] Abridged view of latest flight
